version: '3'
services:
  authentication:
    build: 
      dockerfile: ./docker/flask/Dockerfile 
      context: ../
    expose:
      - 80
    links:
      - database
      - session
  frontend:
    build: 
      dockerfile: ./docker/react/Dockerfile 
      context: ../
    ports:
      - 80:80
    links:
      - authentication
  database:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    expose:
        - 27017
    command: mongod --smallfiles --logpath=/dev/null
  session:
    image: redis
    expose:
      - 6379